# Generated by Django 6.0.4 on 2026-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
